---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clamav-platform-numspot-com-v1alpha1-clusterscan
  failurePolicy: Fail
  name: vclusterscan.kb.io
  rules:
  - apiGroups:
    - clamav.platform.numspot.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterscans
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clamav-platform-numspot-com-v1alpha1-nodescan
  failurePolicy: Fail
  name: vnodescan.kb.io
  rules:
  - apiGroups:
    - clamav.platform.numspot.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodescans
  sideEffects: None
