apiVersion: v2
name: clamav-operator
description: Kubernetes Operator for ClamAV antivirus scanning on cluster nodes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - clamav
  - antivirus
  - security
  - operator
  - scanning
home: https://gitlab.tooling.cloudgouv-eu-west-1.numspot.internal/platform-iac/clamav-operator
sources:
  - https://gitlab.tooling.cloudgouv-eu-west-1.numspot.internal/platform-iac/clamav-operator
maintainers:
  - name: Platform Team
    email: platform-team@numspot.com
icon: https://www.clamav.net/assets/clamav-trademark.png
kubeVersion: ">=1.24.0-0"
