apiVersion: v2
name: clamav-operator
description: Kubernetes Operator for ClamAV antivirus scanning on cluster nodes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - clamav
  - antivirus
  - security
  - operator
  - scanning
home: https://github.com/SolucTeam/clamav-operator
sources:
  - https://github.com/SolucTeam/clamav-operator
maintainers:
  - name: ClamAV Operator Contributors
    email: clamav-operator@users.noreply.github.com
icon: https://www.clamav.net/assets/clamav-trademark.png
kubeVersion: ">=1.24.0-0"
