{{- if .Values.monitoring.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "clamav-operator.fullname" . }}-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clamav-operator.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: clamav-operator
    interval: 30s
    rules:
    {{- toYaml .Values.monitoring.prometheusRule.rules | nindent 4 }}
{{- end }}
