apiVersion: v1
kind: Service
metadata:
  name: {{ include "clamav-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clamav-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
    control-plane: controller-manager
spec:
  type: {{ .Values.operator.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.operator.service.metricsPort }}
    protocol: TCP
    targetPort: metrics
  - name: health
    port: {{ .Values.operator.service.healthPort }}
    protocol: TCP
    targetPort: health
  selector:
    {{- include "clamav-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clamav-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clamav-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    {{- include "clamav-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
